version: '3.1'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./_gitlab/config:/etc/gitlab
      - ./_gitlab/data:/var/opt/gitlab
      - ./_gitlab/logs:/var/log/gitlab
    restart: always
